#!/bin/bash

# Korean broken? go https://github.com/inu-appcenter/cafeteria-server-deploy

# 시스템이 시동될 때에 systemd에 의해 실행됩니다.
# 인스턴스를 실행하여 시스템 종료 전과 같은 상태로 되돌립니다.
# start-instance와 달리 nohup을 백그라운드에서 실행하지 않습니다.

CAFETERIA_INSTANCES=~/.cafeteria/instances/

ENVFILE_PATH=~/.cafeteria/exports.sh

HOST=api.inu-cafeteria.app

function determine_which_instance_to_start() {
  target_instance_name=$(enabled-instance)
  target_instance_port=$(enabled-port)

  : ${target_instance_name:="instanceA"}
  : ${target_instance_port:="20201"}
}

function check_if_already_running() {
	if [ ! -z "$(pid $target_instance_name)" ]; then
		echo "$target_instance_name is already running."
		exit 0
	fi
}

function check_if_source_exists() {
	if [ ! -d "$CAFETERIA_INSTANCES/$target_instance_name" ]; then
		echo "$target_instance_name is not downloaded."
		exit 0
	fi
}

function start() {
	source $ENVFILE_PATH

	cd $CAFETERIA_INSTANCES/$target_instance_name

	nohup npm start -- --host=$HOST --port=$target_instance_port --log-dir=../logs
}

determine_which_instance_to_start $@ &&
check_if_already_running &&
check_if_source_exists &&
start
