#!/bin/bash

# Korean broken? go https://github.com/inu-appcenter/cafeteria-server-deploy

# 저장소로부터 앱을 다운로드하고 nginx 설정을 교체합니다.

REPO=https://github.com/inu-appcenter/cafeteria-server.git

CAFETERIA_HOME=~/.cafeteria/

function check_if_not_installed() {
  if [ ! -d "$CAFETERIA_HOME" ]; then
    echo "Cafeteria not installed. Please install and try again."
    exit 1
  fi
}

function determine_which_instance_to_use() {
  if [ $# -eq 0 ]; then
    target_instance_name=$(disabled-instance)
    target_instance_port=$(disabled-port)
  elif [[ "$1" =~ ^(a|A|instanceA)$ ]]; then
    target_instance_name="instanceA"
    target_instance_port="20201"
  elif [[ "$1" =~ ^(b|B|instanceB)$ ]]; then
    target_instance_name="instanceB"
    target_instance_port="20202"
  else
    usage
  fi

  : ${target_instance_name:="instanceA"}
  : ${target_instance_port:="20201"}
}

function completed() {
  echo "Successfully deployed." &&
  status
}

check_if_not_installed &&
determine_which_instance_to_use &&
update-instance $target_instance_name -f && # no ask.
start-instance $target_instance_name &&
connect-to-nginx $target_instance_name -f && # no ask.
completed
