#!/bin/bash

# Korean broken? go https://github.com/inu-appcenter/cafeteria-server-deploy

# 활성화된 인스턴스의 이름을 가져옵니다. 없을 때에는 아무 것도 출력하지 않습니다.
# 예시: instanceA

function print_instance_name() {
  if [ "$(is-nginx-set)" == "N" ]; then
    exit 1
  fi

  config_prefix='cafeteria_'
  enabled_instance_name=$(ls /etc/nginx/conf.d/$config_prefix*.conf | head -1 | gawk "match(\$0, /.*$config_prefix(.+).conf/, arr) { print arr[1]}")

  echo $enabled_instance_name
}

print_instance_name
