#!/bin/bash

# Korean broken? go https://github.com/inu-appcenter/cafeteria-server-deploy

# 활성화된 인스턴스의 이름을 가져옵니다. 없을 때에는 아무 것도 출력하지 않습니다.
# 예시: instanceA

function print_instance_name() {
  config_prefix=''
  enabled_instance_name=$(ls /etc/nginx/conf.d/cafeteria_*.conf 2> /dev/null | head -1 | gawk "match(\$0, /.*cafeteria_(.+).conf/, arr) { print arr[1]}")

  echo $enabled_instance_name
}

print_instance_name
