#!/bin/bash

# Korean broken? go https://github.com/inu-appcenter/cafeteria-server-deploy

# 앱 배포를 위한 제반 시설을 설치합니다.
# 1. 스크립트를 ~/.cafeteria/bin으로 이동하고 ~/.profile을 수정하여 PATH에 추가합니다.
# 2. 아파치 설정 파일(예비용 포함)을 ~/.cafeteria/conf.d 로 복사합니다.
# 3. ~/.cafeteria/exports.sh 파일을 생성하고 사용자에게 내용을 추가하도록 유도합니다.
# 4. deploy를 실행합니다.

# 설치 경로는 고정입니다.
CAFETERIA_HOME=~/.cafeteria/
CAFETERIA_BIN=~/.cafeteria/bin/
CAFETERIA_CONFIGS=~/.cafeteria/conf.d/
CAFETERIA_INSTANCES=~/.cafeteria/instances/

THIS_SCRIPT_PATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

function is_already_installed() {
  if [ -d "$CAFETERIA_HOME" ]; then
    echo "Cafeteria already installed. Please uninstall and try again."
    exit 1
  fi
}

function ask() {
  echo "This will install INU Cafeteria applicatoin to this server."
  read -p "Proceed? [Y/n] " -n 1 -r

  echo    # (optional) move to a new line

  if [[ $REPLY =~ ^[Yy]$ ]] || [ "$REPLY" == "" ]
  then
    echo "OK."
  else
    echo "Cancel."
    exit 1
  fi
}

function create_directories() {
  mkdir -p $CAFETERIA_HOME &&
  mkdir -p $CAFETERIA_BIN &&
  mkdir -p $CAFETERIA_CONFIGS &&
  mkdir -p $CAFETERIA_INSTANCES &&
  echo "Created install directories."
}

function copy_scripts() {
  cp $THIS_SCRIPT_PATH/* $CAFETERIA_BIN/ &&
  echo "Copied scripts."
}

function copy_nginx_configs() {
  cp $THIS_SCRIPT_PATH/../conf.d/* $CAFETERIA_CONFIGS/ &&
  echo "Copied nginx configs."
}

function append_path() {
  echo 'PATH="$HOME/.cafeteria/bin:$PATH"' >> ~/.profile &&
  source ~/.profile &&
  echo "Registered path."
}

function create_env_file() {
  file=$CAFETERIA_HOME/exports.sh

  echo '#!/bin/bash' >> $file &&
  echo '' >> $file &&
  echo '# Please fill the blanks. No idea? call 010-2922-2661.' >> $file &&
  echo '' >> $file &&
  echo 'export NODE_ENV=' >> $file &&
  echo 'export JWT_SECRET_KEY=' >> $file &&
  echo 'export DB_USERNAME=' >> $file &&
  echo 'export DB_PASSWORD=' >> $file &&
  echo 'export LOGIN_KEY=' >> $file &&
  echo 'export TEST_ID=' >> $file &&
  echo 'export TEST_PW=' >> $file &&
  echo "Created env file." &&
  vi $file
}

function execute_deploy() {
  echo "Deploying app..." &&
  deploy &&
  echo "Deployed app."
}

function completed() {
  echo "Installation & deployment successfully completed." &&
  echo "Please type 'source ~/.profile' in your shell to use server commands."
}

is_already_installed &&
ask &&
create_directories &&
copy_scripts &&
append_path &&
create_env_file &&
execute_deploy &&
completed
