#!/bin/bash

# 현재 지정된 인스턴스가 준비되었는지 확인합니다.
# Check if currently enabled instance is ready.

function is_ready() {
	instance=$(enabled-instance)
	
	if [ -z "$instance" ]; then
		exit 1
	fi

	if [ -d "$(deploy-path)/$instance" ]
	then
		echo "Y"
	else
		echo "N"
	fi
}

is_ready
