#!/bin/bash

# 서버가 제대로 돌아가고 있는지 알려줍니다. 결과는 Y 아니면 N.
# Check if the server is running. Prints Y or N.

function is_running() {
	pid=$(pid)

	if [ -z "$pid" ]
	then
		echo "N"
	else
		echo "Y"
	fi
}

is_running
