#!/bin/bash

# Korean broken? go https://github.com/inu-appcenter/cafeteria-server-deploy

# 애플리케이션을 시작합니다.

CAFETERIA_INSTANCES=~/.cafeteria/instances/

ENVFILE_PATH=~/.cafateria/exports.sh

HOST=api.inu-cafeteria.app

function determine_which_instance_to_start() {
  if [ $# -eq 0 ]; then
    target_instance_name=$(enabled-instance)
    target_instance_port=$(enabled-port)
  elif [[ "$1" =~ ^(a|A|instanceA)$ ]]; then
    target_instance_name="instanceA"
    target_instance_port="20201"
  elif [[ "$1" =~ ^(b|B|instanceB)$ ]]; then
    target_instance_name="instanceB"
    target_instance_port="20202"
  else
    usage
  fi

  : ${target_instance_name:="instanceA"}
  : ${target_instance_port:="20201"}
}

function check_if_already_running() {
	if [ ! -z "$(pid $target_instance_name)" ]; then
		echo "$target_instance_name is already running!"
		exit 1
	fi
}

function start() {
	source $ENVFILE_PATH

  cd $CAFETERIA_INSTANCES/$target_instance_name

 	nohup npm start -- --host=$HOST --port=$target_instance_port --log-dir=../logs > /dev/null || exit 1 &
}

function wait() {
	echo "Waiting for process"
	while [ -z "$(pid $target_instance_name)" ]; do
		echo -n "."
		sleep 0.5
	done
	echo "$target_instance_name started."
}

determine_which_instance_to_start $@ &&
check_if_already_running &&
start &&
wait
